### ISSUE TITLE
Tunguska - at the same playing level like GNUChess 6.2.4 ?

### ISSUE THREAD

**Issue by ChessGUI** [fernandotenorio/Tunguska#1]
Hello Fernando,

has your engine the same playing strength like GNUChess 6.2.4 for Mac OS X?
The GNU source code is here available: https://www.gnu.org/software/chess/ - http://ftp.gnu.org/gnu/chess/

Can you build a Macintosh binary of GNUChess and host it on your website too?

GNU website is maintained by Antonio Ceballos (email>cf. authors) , but he uses Linux, not Max OS X.

GUIs for UCI/WB-comapatible engines ~ http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list (CCWiki)

GNUChess 6.2.4  can be used as pure WB program  http://hgm.nubati.net/CECP.html or via Universal Chess Interface http://www.shredderchess.com/download.html - in this case a commandline-parameter -u is necessary

**Comment by fernandotenorio** [comment]
It play's around 2200-2300 on fast time controls.
